#!/bin/bash

# ce script change les extensions des fichiers
# selon la syntaxe nom-de-fichier.extension-de-fichier

if [ $# -ne 2 ]; then
	echo "Usage : $0 <ancienne-extension> <nouvelle-extension>"
	exit 1
fi

for i in *.*
do
	mv "$i" "`basename -s .$1 $i`.$2"
done